language: ruby
rvm:
  - 2.2
  - 2.3
sudo: required
dist: trusty
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler
  - gem --version
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
addons:
    code_climate:
        repo_token: 9f3ed69eaf4cd5087f34c19d2e74f2457cdd1ae031cc43d0c1be308675e95823
after_success:
  - bundle exec codeclimate-test-reporter

